### ISSUE TITLE
Unify runtime usage counters name

### ISSUE THREAD

**Issue by pwalski** [golemfactory/ya-runtime-ai#107]
Unify runtime counter names so all of them will use underscore separator
```
"golem.usage.duration_sec",
"golem.usage.gpu_sec"
```
(update counter names in runtime `main.rs`, offer template, gamerhash-facade automatic descriptor, golem lib code & tests)

**Comment by nieznanysprawiciel** [comment]
We are migrating in opposite direction

**Comment by pwalski** [comment]
that was fast
