### ISSUE TITLE
vcruntime140.dll absent again

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/ya-runtime-ai#112]
![Image](https://github.com/golemfactory/ya-runtime-ai/assets/10420306/d599ebdc-5677-463c-8f9c-55e9c87b25c6)

Happened on: [pre-rel-v4.1.0-rc5](https://github.com/golemfactory/gamerhash-facade/releases/tag/pre-rel-v4.1.0-rc5)

**Comment by pwalski** [comment]
Release https://github.com/golemfactory/gamerhash-facade/releases/tag/pre-rel-v4.1.0-rc8 contains this change.
It got verified on host 53. I will update other hosts.
