### ISSUE TITLE
Facade job creation flow

### ISSUE THREAD

**Issue by staszek-krotki** [golemfactory/ya-runtime-ai#6]
After yagna/ya-provider is started and a job has been ran.

- CurrentJob is filled in, wait on agreement endpoints
- monitor `/activity` - if it was deleted, check its status

Statuses updated:
- Status
- PaymentStatus

Job creation scenario:
- initial state: yagna started/ready to accept tasks
- job arrives - `CurrentJob` returns not `null`, we receive `CurrentJob` notification event
- `JobStatus` notification arrives
- `Payment` notification arrives
- check if `reward` increases (optional???)
- the moment `JobStatus` is finished `CurrentJob` should turn `null`

Implementation should set:
- job.id = agreement_id.
- jo.brequestor_id = requestor_id.

Functional test including execution of sample activity/task/yapapi app

**Comment by pwalski** [comment]
It still needs:
[ ] Functional tests (iron python starting yapapi tasks + scenarios)
[ ] Payment notifications
[ ] Job status updates
