### ISSUE TITLE
Choose graphic card to be used by framework

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/ya-runtime-ai#65]
Consider making GPU configurable in other way than providing device UUID property.
(GPU UUID configuration introduced in https://github.com/golemfactory/ya-runtime-ai/pull/76)

**Comment by pwalski** [comment]
Check if it is used https://github.com/golemfactory/ya-runtime-ai/blob/9492894a45daf314d700c8a424ce32d6f01fb778/src/process/automatic/config.rs#L39

**Comment by pwalski** [comment]
GPU is configurable through UUID, there is no other way to configure it.
There were no requests to implement it.
