### ISSUE TITLE
ya-runtime-ai requires vcruntime.dll

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/ya-runtime-ai#71]
https://discord.com/channels/687954211702439971/1217159089679765624/1217161338154123455

Possibly prepare self-contained executable

**Comment by pwalski** [comment]
`vcruntime.dll` is used by `winapi`
From `cargo build -vv`:
`[winapi 0.3.9] cargo:rustc-cfg=feature="vcruntime"`

Both `ya-runtime-ai` and its dependencies use `winapi`.
I removed direct dependency/usage of `winapi` and `vcruntime.dll` still got loaded (it can be check with `resmon.exe` -> CPU -> Associated Processes).

**Comment by pwalski** [comment]
I will use this https://crates.io/crates/static_vcruntime
