### ISSUE TITLE
Job status after app termination before payment

### ISSUE THREAD

**Issue by pwalski** [golemfactory/ya-runtime-ai#80]
Check and test gh facade behavior on following scenario:
1. Provider receives a Job
2. Computation takes long enough to receive partial payments
3. User kills gh facade app after Job termination but before receiving the final payment
Check what will be status of the job after starting the gh facade app.

Related to question on gh channel: https://discord.com/channels/687954211702439971/1159792423296303134/1222465777324654592

**Comment by nieznanysprawiciel** [comment]
Status will be Interrupted. It is standard scenario where Provider kills application during computations, partial payments don't affect Job status.
This behavior will be implemented and confirmed by tests in task: https://github.com/golemfactory/gamerhash-facade/issues/152
